# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('facebookId', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('gender', models.CharField(blank=True, max_length=1, verbose_name='Gender')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Facebook Users',
            },
        ),
    ]
